---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  namespace: demo
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: podinfod
      containers:
      - image: stefanprodan/podinfo:2.1.3
        name: podinfod
